{
  "apiVersion": "argoproj.io/v1alpha1",
  "kind": "Application",
  "metadata": {
    "name": "grafana",
    "namespace": "argocd"
  },
  "spec": {
    "destination": {
      "namespace": "grafana",
      "server": "https://kubernetes.default.svc"
    },
    "project": "default",
    "source": {
      "directory": {
        "include": "{*.json,*.yml,*.yaml}",
        "recurse": true
      },
      "path": "apps/generated/grafana",
      "repoURL": "https://github.com/Pluggi/homelab.git",
      "targetRevision": "main"
    }
  }
}